collections:
  services:
    name: Услуги
    output: true
    permalink: "/:collection/:title/"
  articles:
    name: Статьи
    output: true
    permalink: "/:collection/:title/"
  jekyll_plugins:
defaults:
  - scope:
      path: "services"
      type: services
    values:
      layout: docs
  - scope:
      path: "articles"
      type: articles
    values:
      layout: docs
